### PR TITLE
Parabola primitive

### PR DESCRIPTION
**Pull request by Mateasek**
Raysect Parabola primitive meshing. Parabola is separated into cicular base and parabolic cap which are welded together. The parabolic shape is achieved by vertex lifting.

### CODE REVIEW

**Comment by Mateasek** [comment]
I forgot to comment that the parabole shape is adopted from raysect: https://github.com/raysect/source/blob/0973260f115212aa954ad103080f465ffed78a11/raysect/primitive/parabola.pyx#L359

**Comment by mattngc** [comment]
Hey Matej, are you ready for me to review and test this?

**Comment by Mateasek** [comment]
Hi Matt, yes I think you can review in. This only adds a parabola primitive, which is I think the only missing primitive. I was a bit puzzled at the beginning what actually height and radius refers to. At the end I just rewrote the equation used in the [contains](https://github.com/raysect/source/blob/0973260f115212aa954ad103080f465ffed78a11/raysect/primitive/parabola.pyx#L359) method of the primitive.

 I thought I will raise an issue that the Raysect primitive could have some properties referring to some parameters which are used in mathematical description of parabolic functions as for example latus rectum and focal length. Or at least add some comment in the documentation.

**Comment by mattngc** [comment]
Ok, I'll review it soon.

Sure, that is a fair point about the parabola documentation and properties. Feel free to add a Raysect issue on that point.

**Comment by Mateasek** [comment]
Thanks

I will raise the issue.

**Review by mattngc — APPROVED** [review]
Looks good overall

**Pull request merged**
